// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLEBcQbWlk6ZLiw3DFg2yGOYKAEjnqt0',
    appId: '1:471374277962:web:8f450bb595936c90e0e5b3',
    messagingSenderId: '471374277962',
    projectId: 'ruangbuku-dfd1e',
    authDomain: 'ruangbuku-dfd1e.firebaseapp.com',
    storageBucket: 'ruangbuku-dfd1e.firebasestorage.app',
    measurementId: 'G-R0PFCQ5HSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUhJuyssD1xXFC1XcXDlTWFGRrl1H8JA',
    appId: '1:471374277962:android:567ff4a86766652ae0e5b3',
    messagingSenderId: '471374277962',
    projectId: 'ruangbuku-dfd1e',
    storageBucket: 'ruangbuku-dfd1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYJZ_cfRV0nohtyXFWYH1ife6ZaW4s2c',
    appId: '1:471374277962:ios:c279fc06f023546be0e5b3',
    messagingSenderId: '471374277962',
    projectId: 'ruangbuku-dfd1e',
    storageBucket: 'ruangbuku-dfd1e.firebasestorage.app',
    iosBundleId: 'com.example.ruangbuku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYJZ_cfRV0nohtyXFWYH1ife6ZaW4s2c',
    appId: '1:471374277962:ios:c279fc06f023546be0e5b3',
    messagingSenderId: '471374277962',
    projectId: 'ruangbuku-dfd1e',
    storageBucket: 'ruangbuku-dfd1e.firebasestorage.app',
    iosBundleId: 'com.example.ruangbuku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqLEBcQbWlk6ZLiw3DFg2yGOYKAEjnqt0',
    appId: '1:471374277962:web:3c7612822941bd3de0e5b3',
    messagingSenderId: '471374277962',
    projectId: 'ruangbuku-dfd1e',
    authDomain: 'ruangbuku-dfd1e.firebaseapp.com',
    storageBucket: 'ruangbuku-dfd1e.firebasestorage.app',
    measurementId: 'G-2LWVWPQD1Z',
  );
}
